Implement code annotations.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -45,9 +45,39 @@ compilation_warning_count() {
     echo "$1" | egrep -o "[0-9]+ warnings?$" | sed "s/[^0-9]//g" || echo "0"
 }
 
+explain_compilation_error() {
+    echo ""
+}
+
 parse_compilation_error() {
     dodona_start_context
+
+    # Print the compilation message.
     dodona_start_testcase_code_message "$1"
+
+    # Try to explain this compilation message, add it to the testcase if found.
+    explanation=$(explain_compilation_error "$1")
+    [[ "$explanation" == "" ]] || dodona_append_plain_message "$explanation"
+
+    # Get the code annotation information and annotate the code.
+    annotation_column=$(echo "$1" | grep -o "\s*\^" | wc -c)
+    annotation_column=$((annotation_column - 2))
+    annotation_row=$(echo "$1" | sed "s/^$filename:\([0-9]\+\):.*/\1/g")
+    annotation_row=$((annotation_row - 1))
+    annotation_is_error=$(echo "$1" | grep -c "^$filename:[0-9]\+: error" || true)
+
+    if [[ "$explanation" == "" ]]; then
+        annotation_text=$(echo -e "$1" | sed "s/.*: error://" | sed "s/.*: warning://" | head -n 1)
+    else
+        annotation_text="$explanation"
+    fi
+
+    if [[ "$annotation_is_error" == "1" ]]; then
+        dodona_annotate_code_error "$annotation_row" "$annotation_column" "$annotation_text"
+    else
+        dodona_annotate_code_warning "$annotation_row" "$annotation_column" "$annotation_text"
+    fi
+
     dodona_close_failed_testcase
     dodona_close_failed_context
 }
